kind: pipeline
name: ldapauthd


steps:
  - name: Run tests and build
    image: golang:latest
    commands:
      - go fmt
      - go vet
      - go test
      - go build
    when:
      event:
      - pull_request

- name: Build image and publish
    image: plugins/docker
    settings:
      repo: rg.nl-ams.scw.cloud/revlabs/ldapauthd
      username: nologin
      password:
        from_secret: SCW_SECRET_KEY
      registry: rg.nl-ams.scw.cloud/revlabs
      autotag: true
    when:
      event:
        - push
        - tag
      branch:
        - master